mod GEO-INIT is   
  protecting GEO-DEFINITION .
  protecting GEO-FUNCS .
  protecting GEO-PETROLEUM .  
  protecting NAT .


  op caseStudy-unknown-submarinefan : -> Configuration [ctor] . 
  eq caseStudy-unknown-submarinefan
  = < GeoUnit | Ocnt: 17 > 
   < Hydrocarbon | Ocnt: 0 > 
   < Fault | Ocnt: 4 > 
   < Pathways | Pathways: nil, Ocnt: 0 > 

   < 0 : Fault | FType: normalfault, Filling: non-sealing, InContactWith: (4,1,dippingAway,hangingWall,0) :: ((5,2,dippingAway,hangingWall,7) :: ((6,3,dippingAway,hangingWall,8) ::
                                                                          ((16,16,dippingAway,hangingWall,9) :: ((0,0,dippingTowards,footWall,4) :: 
		                                                          ((7,1,dippingTowards,footWall,5) :: ((8,2,dippingTowards,footWall,6) :: ((9,3,dippingTowards,footWall,16) :: nil))))))), Time: timeOf(Fault,0) >

   < 1 : Fault | FType: normalfault, Filling: non-sealing, InContactWith: (7,1,dippingAway,hangingWall,0) :: ((7,1,dippingAway,hangingWall,10) :: ((8,2,dippingAway,hangingWall,10) :: ((8,2,dippingAway,hangingWall,11) :: ((9,3,dippingAway,hangingWall,11) ::
				                                          ((9,3,dippingAway,hangingWall,12) :: ((16,16,dippingAway,hangingWall,12) :: ((0,0,dippingTowards,footWall,7) :: 
			                                                  ((10,1,dippingTowards,footWall,7) :: ((10,1,dippingTowards,footWall,8) :: ((11,2,dippingTowards,footWall,8) ::
				                                          ((11,2,dippingTowards,footWall,9) :: ((12,3,dippingTowards,footWall,9) :: ((12,3,dippingTowards,footWall,16) :: nil))))))))))))), Time: timeOf(Fault,1) >

   < 2 : Fault | FType: normalfault, Filling: non-sealing, InContactWith: (10,1,dippingAway,hangingWall,0) :: ((11,2,dippingAway,hangingWall,13) :: ((12,3,dippingAway,hangingWall,14) ::
				                                          ((16,16,dippingAway,hangingWall,15) :: ((0,0,dippingTowards,footWall,10) ::
			                                                  ((13,1,dippingTowards,footWall,11) ::
				                                          ((14,2,dippingTowards,footWall,12) :: ((15,3,dippingTowards,footWall,16) :: nil))))))), Time: timeOf(Fault,2) >

   < 3 : Fault | FType: normalfault, Filling: sealing, InContactWith:     (13,1,dippingAway,hangingWall,null) :: ((14,2,dippingAway,hangingWall,null) :: ((15,3,dippingAway,hangingWall,null) :: nil)), Time: timeOf(Fault,3) >	

   < 0 : GeoUnit  | GeoUnit: 0, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,0), Role: noRole, 
		 InContactWith: 13 :: (10 :: (7 :: (4 :: nil))), KerogenType: "none", Hydrocarbon: null >
	
   < 4 : GeoUnit  | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 5 :: nil, KerogenType: "3", Hydrocarbon: null > 
   < 5 : GeoUnit  | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: unknown, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 4 :: (6 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 6 : GeoUnit  | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole, 
		 InContactWith: 5 :: nil, KerogenType: "none", Hydrocarbon: null >
	  
   < 7 : GeoUnit  | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 8 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 8 : GeoUnit  | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: unknown, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 7 :: (9 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 9 : GeoUnit  | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole, 
		 InContactWith: 8 :: nil, KerogenType: "none", Hydrocarbon: null >

   < 10 : GeoUnit | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 11 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 11 : GeoUnit | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: unknown, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole,
		 InContactWith: 10 :: (12 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 12 : GeoUnit | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole,
		 InContactWith: 11 :: nil, KerogenType: "none", Hydrocarbon: null >
	
   < 13 : GeoUnit | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 14 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 14 : GeoUnit | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: unknown, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 13 :: (15 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 15 : GeoUnit | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole,
		 InContactWith: 14 :: nil, KerogenType: "none", Hydrocarbon: null >	

   < 16 : GeoUnit | GeoUnit: 16, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,16), Role: noRole,
		 InContactWith: 15 :: (12 :: (9 :: (6 :: nil))), KerogenType: "none", Hydrocarbon: null >  

   ageComparison(younger(timeOf(GeoUnit,16),timeOf(GeoUnit,3)) :: younger(timeOf(GeoUnit,3),timeOf(GeoUnit,2)) ::
	         younger(timeOf(GeoUnit,2),timeOf(GeoUnit,1)) :: younger(timeOf(GeoUnit,1),timeOf(GeoUnit,0)))
	
   depositionalContact((3,16) :: ((2,3) :: ((1,2) :: ((0,1) :: nil))))		    	
   younger(timeOf(Migration),timeOf(Fault,0)) 

   --- default values ---
   trapformation(5,none,nil,undefined) trapformation(8,none,nil,undefined) trapformation(11,none,nil,undefined) trapformation(14,none,nil,undefined)
   accumulation(5,false) accumulation(8,false) accumulation(11,false) accumulation(14,false) 
   history("init") .    

    
  op caseStudy0 : -> Configuration [ctor] .  
  eq caseStudy0
  = < GeoUnit | Ocnt: 17 > 
   < Hydrocarbon | Ocnt: 0 > 
   < Fault | Ocnt: 4 > 
   < Pathways | Pathways: nil, Ocnt: 0 > 

   < 0 : Fault | FType: normalfault, Filling: non-sealing, InContactWith: (4,1,dippingAway,hangingWall,0) :: ((5,2,dippingAway,hangingWall,7) :: ((6,3,dippingAway,hangingWall,8) ::
                                                                          ((16,16,dippingAway,hangingWall,9) :: ((0,0,dippingTowards,footWall,4) :: 
		                                                          ((7,1,dippingTowards,footWall,5) :: ((8,2,dippingTowards,footWall,6) :: ((9,3,dippingTowards,footWall,16) :: nil))))))),
		                                                          Time: timeOf(Fault,0) >  

   < 1 : Fault | FType: normalfault, Filling: non-sealing, InContactWith: (7,1,dippingAway,hangingWall,0) :: ((7,1,dippingAway,hangingWall,10) :: ((8,2,dippingAway,hangingWall,10) ::
			                                                  ((8,2,dippingAway,hangingWall,11) :: ((9,3,dippingAway,hangingWall,11) ::
				                                          ((9,3,dippingAway,hangingWall,12) :: ((16,16,dippingAway,hangingWall,12) :: ((0,0,dippingTowards,footWall,7) :: 
			                                                  ((10,1,dippingTowards,footWall,7) :: ((10,1,dippingTowards,footWall,8) :: ((11,2,dippingTowards,footWall,8) ::
				                                          ((11,2,dippingTowards,footWall,9) :: ((12,3,dippingTowards,footWall,9) :: ((12,3,dippingTowards,footWall,16) :: nil))))))))))))),
		                                                          Time: timeOf(Fault,1) >  

   < 2 : Fault | FType: normalfault, Filling: non-sealing, InContactWith: (10,1,dippingAway,hangingWall,0) :: ((11,2,dippingAway,hangingWall,13) :: ((12,3,dippingAway,hangingWall,14) ::
				                                          ((16,16,dippingAway,hangingWall,15) :: ((0,0,dippingTowards,footWall,10) ::
			                                                  ((13,1,dippingTowards,footWall,11) :: ((14,2,dippingTowards,footWall,12) :: ((15,3,dippingTowards,footWall,16) :: nil))))))),
		                                                          Time: timeOf(Fault,2) > 
	
   < 3 : Fault | FType: normalfault, Filling: sealing, InContactWith:     (13,1,dippingAway,hangingWall,null) :: ((14,2,dippingAway,hangingWall,null) :: ((15,3,dippingAway,hangingWall,null) :: nil)),    
                                                                          Time: timeOf(Fault,3) >

	
   < 0 : GeoUnit  | GeoUnit: 0, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,0), Role: noRole, 
		 InContactWith: 13 :: (10 :: (7 :: (4 :: nil))), KerogenType: "none", Hydrocarbon: null >
	
   < 4 : GeoUnit  | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole,
		 InContactWith: 5 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 5 : GeoUnit  | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: distributaryChannel, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 4 :: (6 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 6 : GeoUnit  | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole, 
		 InContactWith: 5 :: nil, KerogenType: "none", Hydrocarbon: null >
	  
   < 7 : GeoUnit  | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 8 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 8 : GeoUnit  | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: interChannel, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 7 :: (9 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 9 : GeoUnit  | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole, 
		 InContactWith: 8 :: nil, KerogenType: "none", Hydrocarbon: null >

   < 10 : GeoUnit | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 11 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 11 : GeoUnit | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: lobe, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole,
		 InContactWith: 10 :: (12 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 12 : GeoUnit | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole,
		 InContactWith: 11 :: nil, KerogenType: "none", Hydrocarbon: null >
	
   < 13 : GeoUnit | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 14 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 14 : GeoUnit | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: lobeFringe, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 13 :: (15 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 15 : GeoUnit | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole,
		 InContactWith: 14 :: nil, KerogenType: "none", Hydrocarbon: null >	

   < 16 : GeoUnit  | GeoUnit: 16, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,16), Role: noRole,
		 InContactWith: 15 :: (12 :: (9 :: (6 :: nil))), KerogenType: "none", Hydrocarbon: null >  

   ageComparison(younger(timeOf(GeoUnit,16),timeOf(GeoUnit,3)) :: younger(timeOf(GeoUnit,3),timeOf(GeoUnit,2)) ::
	         younger(timeOf(GeoUnit,2),timeOf(GeoUnit,1)) :: younger(timeOf(GeoUnit,1),timeOf(GeoUnit,0)))
	
   depositionalContact((3,16) :: ((2,3) :: ((1,2) :: ((0,1) :: nil))))		    	
	
   --- default values ---
   trapformation(5,none,nil,undefined) trapformation(8,none,nil,undefined) trapformation(11,none,nil,undefined) trapformation(14,none,nil,undefined)
   accumulation(5,false) accumulation(8,false) accumulation(11,false) accumulation(14,false) 
   history("init") .

       
  op caseStudy1-0 : -> Configuration [ctor] . 
  eq caseStudy1-0
  = < GeoUnit | Ocnt: 17 > 
   < Hydrocarbon | Ocnt: 0 > 
   < Fault | Ocnt: 4 > 
   < Pathways | Pathways: nil, Ocnt: 0 > 

   < 0 : Fault | FType: normalfault, Filling: non-sealing, InContactWith: (4,1,dippingAway,hangingWall,0) :: ((5,2,dippingAway,hangingWall,7) :: ((6,3,dippingAway,hangingWall,8) ::
                                                                          ((16,16,dippingAway,hangingWall,9) :: ((0,0,dippingTowards,footWall,4) :: 
		                                                          ((7,1,dippingTowards,footWall,5) :: ((8,2,dippingTowards,footWall,6) :: ((9,3,dippingTowards,footWall,16) :: nil))))))), Time: timeOf(Fault,0) >

   < 1 : Fault | FType: normalfault, Filling: non-sealing, InContactWith: (7,1,dippingAway,hangingWall,0) :: ((7,1,dippingAway,hangingWall,10) :: ((8,2,dippingAway,hangingWall,10) :: ((8,2,dippingAway,hangingWall,11) :: ((9,3,dippingAway,hangingWall,11) ::
				                                          ((9,3,dippingAway,hangingWall,12) :: ((16,16,dippingAway,hangingWall,12) :: ((0,0,dippingTowards,footWall,7) :: 
			                                                  ((10,1,dippingTowards,footWall,7) :: ((10,1,dippingTowards,footWall,8) :: ((11,2,dippingTowards,footWall,8) ::
				                                          ((11,2,dippingTowards,footWall,9) :: ((12,3,dippingTowards,footWall,9) :: ((12,3,dippingTowards,footWall,16) :: nil))))))))))))), Time: timeOf(Fault,1) >

   < 2 : Fault | FType: normalfault, Filling: non-sealing, InContactWith: (10,1,dippingAway,hangingWall,0) :: ((11,2,dippingAway,hangingWall,13) :: ((12,3,dippingAway,hangingWall,14) ::
				                                          ((16,16,dippingAway,hangingWall,15) :: ((0,0,dippingTowards,footWall,10) ::
			                                                  ((13,1,dippingTowards,footWall,11) ::
				                                          ((14,2,dippingTowards,footWall,12) :: ((15,3,dippingTowards,footWall,16) :: nil))))))), Time: timeOf(Fault,2) >

   < 3 : Fault | FType: normalfault, Filling: sealing, InContactWith:     (13,1,dippingAway,hangingWall,null) :: ((14,2,dippingAway,hangingWall,null) :: ((15,3,dippingAway,hangingWall,null) :: nil)), Time: timeOf(Fault,3) >	

	
   < 0 : GeoUnit  | GeoUnit: 0, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,0), Role: noRole, 
		 InContactWith: 13 :: (10 :: (7 :: (4 :: nil))), KerogenType: "none", Hydrocarbon: null >
	
   < 4 : GeoUnit  | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 5 :: nil, KerogenType: "3", Hydrocarbon: null > 
   < 5 : GeoUnit  | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: distributaryChannel, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 4 :: (6 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 6 : GeoUnit  | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole, 
		 InContactWith: 5 :: nil, KerogenType: "none", Hydrocarbon: null >
	  
   < 7 : GeoUnit  | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 8 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 8 : GeoUnit  | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: distributaryChannel, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 7 :: (9 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 9 : GeoUnit  | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole, 
		 InContactWith: 8 :: nil, KerogenType: "none", Hydrocarbon: null >

   < 10 : GeoUnit | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 11 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 11 : GeoUnit | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: lobe, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole,
		 InContactWith: 10 :: (12 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 12 : GeoUnit | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole,
		 InContactWith: 11 :: nil, KerogenType: "none", Hydrocarbon: null >
	
   < 13 : GeoUnit | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 14 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 14 : GeoUnit | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: lobeFringe, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 13 :: (15 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 15 : GeoUnit | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole,
		 InContactWith: 14 :: nil, KerogenType: "none", Hydrocarbon: null >	

   < 16 : GeoUnit | GeoUnit: 16, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,16), Role: noRole,
		 InContactWith: 15 :: (12 :: (9 :: (6 :: nil))), KerogenType: "none", Hydrocarbon: null >  

   ageComparison(younger(timeOf(GeoUnit,16),timeOf(GeoUnit,3)) :: younger(timeOf(GeoUnit,3),timeOf(GeoUnit,2)) ::
	         younger(timeOf(GeoUnit,2),timeOf(GeoUnit,1)) :: younger(timeOf(GeoUnit,1),timeOf(GeoUnit,0)))
	
   depositionalContact((3,16) :: ((2,3) :: ((1,2) :: ((0,1) :: nil))))		    	
   younger(timeOf(Migration),timeOf(Fault,0)) 

   --- default values ---
   trapformation(5,none,nil,undefined) trapformation(8,none,nil,undefined) trapformation(11,none,nil,undefined) trapformation(14,none,nil,undefined)
   accumulation(5,false) accumulation(8,false) accumulation(11,false) accumulation(14,false) 
   history("init") .

    
    
  op caseStudy1-1 : -> Configuration [ctor] . 
  eq caseStudy1-1
  = < GeoUnit | Ocnt: 17 > 
   < Hydrocarbon | Ocnt: 0 > 
   < Fault | Ocnt: 4 > 
   < Pathways | Pathways: nil, Ocnt: 0 > 

   < 0 : Fault | FType: normalfault, Filling: non-sealing, InContactWith: (4,1,dippingAway,hangingWall,0) :: ((5,2,dippingAway,hangingWall,7) :: ((6,3,dippingAway,hangingWall,8) ::
                                                                          ((16,16,dippingAway,hangingWall,9) :: ((0,0,dippingTowards,footWall,4) :: 
		                                                          ((7,1,dippingTowards,footWall,5) :: ((8,2,dippingTowards,footWall,6) :: ((9,3,dippingTowards,footWall,16) :: nil))))))), Time: timeOf(Fault,0) >

   < 1 : Fault | FType: normalfault, Filling: non-sealing, InContactWith: (7,1,dippingAway,hangingWall,0) :: ((7,1,dippingAway,hangingWall,10) :: ((8,2,dippingAway,hangingWall,10) :: ((8,2,dippingAway,hangingWall,11) :: ((9,3,dippingAway,hangingWall,11) ::
				                                          ((9,3,dippingAway,hangingWall,12) :: ((16,16,dippingAway,hangingWall,12) :: ((0,0,dippingTowards,footWall,7) :: 
			                                                  ((10,1,dippingTowards,footWall,7) :: ((10,1,dippingTowards,footWall,8) :: ((11,2,dippingTowards,footWall,8) ::
				                                          ((11,2,dippingTowards,footWall,9) :: ((12,3,dippingTowards,footWall,9) :: ((12,3,dippingTowards,footWall,16) :: nil))))))))))))), Time: timeOf(Fault,1) >

   < 2 : Fault | FType: normalfault, Filling: non-sealing, InContactWith: (10,1,dippingAway,hangingWall,0) :: ((11,2,dippingAway,hangingWall,13) :: ((12,3,dippingAway,hangingWall,14) ::
				                                          ((16,16,dippingAway,hangingWall,15) :: ((0,0,dippingTowards,footWall,10) ::
			                                                  ((13,1,dippingTowards,footWall,11) ::
				                                          ((14,2,dippingTowards,footWall,12) :: ((15,3,dippingTowards,footWall,16) :: nil))))))), Time: timeOf(Fault,2) >

   < 3 : Fault | FType: normalfault, Filling: sealing, InContactWith:     (13,1,dippingAway,hangingWall,null) :: ((14,2,dippingAway,hangingWall,null) :: ((15,3,dippingAway,hangingWall,null) :: nil)), Time: timeOf(Fault,3) >	

	
   < 0 : GeoUnit  | GeoUnit: 0, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,0), Role: noRole, 
		 InContactWith: 13 :: (10 :: (7 :: (4 :: nil))), KerogenType: "none", Hydrocarbon: null >
	
   < 4 : GeoUnit  | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 5 :: nil, KerogenType: "3", Hydrocarbon: null > 
   < 5 : GeoUnit  | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: feederChannel, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 4 :: (6 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 6 : GeoUnit  | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole, 
		 InContactWith: 5 :: nil, KerogenType: "none", Hydrocarbon: null >
	  
   < 7 : GeoUnit  | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 8 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 8 : GeoUnit  | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: distributaryChannel, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 7 :: (9 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 9 : GeoUnit  | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole, 
		 InContactWith: 8 :: nil, KerogenType: "none", Hydrocarbon: null >
				   
   < 10 : GeoUnit | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 11 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 11 : GeoUnit | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: lobe, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole,
		 InContactWith: 10 :: (12 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 12 : GeoUnit | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole,
		 InContactWith: 11 :: nil, KerogenType: "none", Hydrocarbon: null >
	
   < 13 : GeoUnit | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 14 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 14 : GeoUnit | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: lobe, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 13 :: (15 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 15 : GeoUnit | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole,
		 InContactWith: 14 :: nil, KerogenType: "none", Hydrocarbon: null >	

   < 16 : GeoUnit | GeoUnit: 16, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,16), Role: noRole,
		 InContactWith: 15 :: (12 :: (9 :: (6 :: nil))), KerogenType: "none", Hydrocarbon: null >  

   ageComparison(younger(timeOf(GeoUnit,16),timeOf(GeoUnit,3)) :: younger(timeOf(GeoUnit,3),timeOf(GeoUnit,2)) ::
	         younger(timeOf(GeoUnit,2),timeOf(GeoUnit,1)) :: younger(timeOf(GeoUnit,1),timeOf(GeoUnit,0)))
	
   depositionalContact((3,16) :: ((2,3) :: ((1,2) :: ((0,1) :: nil))))		    	
   younger(timeOf(Fault,0),timeOf(Migration))
   younger(timeOf(Migration),timeOf(Fault,3))

   --- default values ---
   trapformation(5,none,nil,undefined) trapformation(8,none,nil,undefined) trapformation(11,none,nil,undefined) trapformation(14,none,nil,undefined)
   accumulation(5,false) accumulation(8,false) accumulation(11,false) accumulation(14,false) 
   history("init") .    


    
  op caseStudy1-2 : -> Configuration [ctor] . 
  eq caseStudy1-2
  = < GeoUnit | Ocnt: 17 > 
   < Hydrocarbon | Ocnt: 0 > 
   < Fault | Ocnt: 4 > 
   < Pathways | Pathways: nil, Ocnt: 0 > 

   < 0 : Fault | FType: normalfault, Filling: non-sealing, InContactWith: (4,1,dippingAway,hangingWall,0) :: ((5,2,dippingAway,hangingWall,7) :: ((6,3,dippingAway,hangingWall,8) ::
                                                                          ((16,16,dippingAway,hangingWall,9) :: ((0,0,dippingTowards,footWall,4) :: 
		                                                          ((7,1,dippingTowards,footWall,5) :: ((8,2,dippingTowards,footWall,6) :: ((9,3,dippingTowards,footWall,16) :: nil))))))), Time: timeOf(Fault,0) >

   < 1 : Fault | FType: normalfault, Filling: non-sealing, InContactWith: (7,1,dippingAway,hangingWall,0) :: ((7,1,dippingAway,hangingWall,10) :: ((8,2,dippingAway,hangingWall,10) :: ((8,2,dippingAway,hangingWall,11) :: ((9,3,dippingAway,hangingWall,11) ::
				                                          ((9,3,dippingAway,hangingWall,12) :: ((16,16,dippingAway,hangingWall,12) :: ((0,0,dippingTowards,footWall,7) :: 
			                                                  ((10,1,dippingTowards,footWall,7) :: ((10,1,dippingTowards,footWall,8) :: ((11,2,dippingTowards,footWall,8) ::
				                                          ((11,2,dippingTowards,footWall,9) :: ((12,3,dippingTowards,footWall,9) :: ((12,3,dippingTowards,footWall,16) :: nil))))))))))))), Time: timeOf(Fault,1) >

   < 2 : Fault | FType: normalfault, Filling: non-sealing, InContactWith: (10,1,dippingAway,hangingWall,0) :: ((11,2,dippingAway,hangingWall,13) :: ((12,3,dippingAway,hangingWall,14) ::
				                                          ((16,16,dippingAway,hangingWall,15) :: ((0,0,dippingTowards,footWall,10) ::
			                                                  ((13,1,dippingTowards,footWall,11) ::
				                                          ((14,2,dippingTowards,footWall,12) :: ((15,3,dippingTowards,footWall,16) :: nil))))))), Time: timeOf(Fault,2) >

   < 3 : Fault | FType: normalfault, Filling: sealing, InContactWith:     (13,1,dippingAway,hangingWall,null) :: ((14,2,dippingAway,hangingWall,null) :: ((15,3,dippingAway,hangingWall,null) :: nil)), Time: timeOf(Fault,3) >	


   < 0 : GeoUnit  | GeoUnit: 0, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,0), Role: noRole, 
		 InContactWith: 13 :: (10 :: (7 :: (4 :: nil))), KerogenType: "none", Hydrocarbon: null >
	
   < 4 : GeoUnit  | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, --- sourceRock,
		 InContactWith: 5 :: nil, KerogenType: "3", Hydrocarbon: null > 
   < 5 : GeoUnit  | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: feederChannel, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 4 :: (6 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 6 : GeoUnit  | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole, 
		 InContactWith: 5 :: nil, KerogenType: "none", Hydrocarbon: null >
	  
   < 7 : GeoUnit  | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 8 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 8 : GeoUnit  | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: distributaryChannel, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 7 :: (9 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 9 : GeoUnit  | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole, 
		 InContactWith: 8 :: nil, KerogenType: "none", Hydrocarbon: null >
				   
   < 10 : GeoUnit | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 11 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 11 : GeoUnit | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: lobe, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole,
		 InContactWith: 10 :: (12 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 12 : GeoUnit | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole,
		 InContactWith: 11 :: nil, KerogenType: "none", Hydrocarbon: null >
	
   < 13 : GeoUnit | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 14 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 14 : GeoUnit | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: lobe, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 13 :: (15 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 15 : GeoUnit | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole,
		 InContactWith: 14 :: nil, KerogenType: "none", Hydrocarbon: null >	

   < 16 : GeoUnit | GeoUnit: 16, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,16), Role: noRole,
		 InContactWith: 15 :: (12 :: (9 :: (6 :: nil))), KerogenType: "none", Hydrocarbon: null >

   ageComparison(younger(timeOf(GeoUnit,16),timeOf(GeoUnit,3)) :: younger(timeOf(GeoUnit,3),timeOf(GeoUnit,2)) ::
	         younger(timeOf(GeoUnit,2),timeOf(GeoUnit,1)) :: younger(timeOf(GeoUnit,1),timeOf(GeoUnit,0)))
	
   depositionalContact((3,16) :: ((2,3) :: ((1,2) :: ((0,1) :: nil))))		    	
   younger(timeOf(Fault,3),timeOf(Migration))	

   --- default values ---
   trapformation(5,none,nil,undefined) trapformation(8,none,nil,undefined) trapformation(11,none,nil,undefined) trapformation(14,none,nil,undefined)
   accumulation(5,false) accumulation(8,false) accumulation(11,false) accumulation(14,false) 
   history("init") .

    
    
  op caseStudy2-0 : -> Configuration [ctor] . 
  eq caseStudy2-0
  = < GeoUnit | Ocnt: 17 > 
   < Hydrocarbon | Ocnt: 0 > 
   < Fault | Ocnt: 4 > 
   < Pathways | Pathways: nil, Ocnt: 0 > 

   < 0 : Fault | FType: normalfault, Filling: non-sealing, InContactWith: (4,1,dippingAway,hangingWall,0) :: ((5,2,dippingAway,hangingWall,0) :: ((5,2,dippingAway,hangingWall,7) :: ((6,3,dippingAway,hangingWall,7) ::
                                                                          ((6,3,dippingAway,hangingWall,8) :: ((16,16,dippingAway,hangingWall,8) :: ((16,16,dippingAway,hangingWall,9) :: ((0,0,dippingTowards,footWall,4) :: 
		                                                          ((0,0,dippingTowards,footWall,5) :: ((7,1,dippingTowards,footWall,5) :: ((7,1,dippingTowards,footWall,6) :: ((8,2,dippingTowards,footWall,6) ::
					                                  ((8,2,dippingTowards,footWall,16) :: ((9,3,dippingTowards,footWall,16) :: nil))))))))))))), Time: timeOf(Fault,0) >

   < 1 : Fault | FType: normalfault, Filling: non-sealing, InContactWith: (7,1,dippingAway,hangingWall,0) :: ((7,1,dippingAway,hangingWall,10) :: ((8,2,dippingAway,hangingWall,10) :: ((8,2,dippingAway,hangingWall,11) :: ((9,3,dippingAway,hangingWall,11) ::
				                                          ((9,3,dippingAway,hangingWall,12) :: ((16,16,dippingAway,hangingWall,12) :: ((0,0,dippingTowards,footWall,7) :: 
			                                                  ((10,1,dippingTowards,footWall,7) :: ((10,1,dippingTowards,footWall,8) :: ((11,2,dippingTowards,footWall,8) ::
				                                          ((11,2,dippingTowards,footWall,9) :: ((12,3,dippingTowards,footWall,9) :: ((12,3,dippingTowards,footWall,16) :: nil))))))))))))), Time: timeOf(Fault,1) >

   < 2 : Fault | FType: normalfault, Filling: non-sealing, InContactWith: (10,1,dippingAway,hangingWall,0) :: ((11,2,dippingAway,hangingWall,13) :: ((12,3,dippingAway,hangingWall,14) ::
				                                          ((16,16,dippingAway,hangingWall,15) :: ((0,0,dippingTowards,footWall,10) ::
			                                                  ((13,1,dippingTowards,footWall,11) ::
				                                          ((14,2,dippingTowards,footWall,12) :: ((15,3,dippingTowards,footWall,16) :: nil))))))), Time: timeOf(Fault,2) >

   < 3 : Fault | FType: normalfault, Filling: sealing, InContactWith:     (13,1,dippingAway,hangingWall,null) :: ((14,2,dippingAway,hangingWall,null) :: ((15,3,dippingAway,hangingWall,null) :: nil)), Time: timeOf(Fault,3) >	

   < 0 : GeoUnit  | GeoUnit: 0, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,0), Role: noRole, 
		 InContactWith: 13 :: (10 :: (7 :: (4 :: nil))), KerogenType: "none", Hydrocarbon: null >
	
   < 4 : GeoUnit  | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 5 :: nil, KerogenType: "3", Hydrocarbon: null > 
   < 5 : GeoUnit  | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: distributaryChannel, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 4 :: (6 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 6 : GeoUnit  | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole, 
		 InContactWith: 5 :: nil, KerogenType: "none", Hydrocarbon: null >
	  
   < 7 : GeoUnit  | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 8 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 8 : GeoUnit  | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: interChannel, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 7 :: (9 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 9 : GeoUnit  | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole, 
		 InContactWith: 8 :: nil, KerogenType: "none", Hydrocarbon: null >

   < 10 : GeoUnit | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 11 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 11 : GeoUnit | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: lobe, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole,
		 InContactWith: 10 :: (12 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 12 : GeoUnit | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole,
		 InContactWith: 11 :: nil, KerogenType: "none", Hydrocarbon: null >
	
   < 13 : GeoUnit | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 14 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 14 : GeoUnit | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: lobeFringe, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 13 :: (15 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 15 : GeoUnit | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole,
		 InContactWith: 14 :: nil, KerogenType: "none", Hydrocarbon: null >	

   < 16 : GeoUnit | GeoUnit: 16, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,16), Role: noRole,
		 InContactWith: 15 :: (12 :: (9 :: (6 :: nil))), KerogenType: "none", Hydrocarbon: null > 

   ageComparison(younger(timeOf(GeoUnit,16),timeOf(GeoUnit,3)) :: younger(timeOf(GeoUnit,3),timeOf(GeoUnit,2)) ::
	         younger(timeOf(GeoUnit,2),timeOf(GeoUnit,1)) :: younger(timeOf(GeoUnit,1),timeOf(GeoUnit,0)))
	
   depositionalContact((3,16) :: ((2,3) :: ((1,2) :: ((0,1) :: nil))))		    	
   younger(timeOf(Migration),timeOf(Fault,0))  

   --- default values ---
   trapformation(5,none,nil,undefined) trapformation(8,none,nil,undefined) trapformation(11,none,nil,undefined) trapformation(14,none,nil,undefined)
   accumulation(5,false) accumulation(8,false) accumulation(11,false) accumulation(14,false) 
   history("init") .


    
  op caseStudy2-1 : -> Configuration [ctor] . 
  eq caseStudy2-1
  = < GeoUnit | Ocnt: 17 > 
   < Hydrocarbon | Ocnt: 0 > 
   < Fault | Ocnt: 4 > 
   < Pathways | Pathways: nil, Ocnt: 0 > 

   < 0 : Fault | FType: normalfault, Filling: non-sealing, InContactWith: (4,1,dippingAway,hangingWall,0) :: ((5,2,dippingAway,hangingWall,0) :: ((5,2,dippingAway,hangingWall,7) :: ((6,3,dippingAway,hangingWall,7) ::
                                                                          ((6,3,dippingAway,hangingWall,8) :: ((16,16,dippingAway,hangingWall,8) :: ((16,16,dippingAway,hangingWall,9) :: ((0,0,dippingTowards,footWall,4) :: 
		                                                          ((0,0,dippingTowards,footWall,5) :: ((7,1,dippingTowards,footWall,5) :: ((7,1,dippingTowards,footWall,6) :: ((8,2,dippingTowards,footWall,6) ::
					                                  ((8,2,dippingTowards,footWall,16) :: ((9,3,dippingTowards,footWall,16) :: nil))))))))))))), Time: timeOf(Fault,0) >

   < 1 : Fault | FType: normalfault, Filling: non-sealing, InContactWith: (7,1,dippingAway,hangingWall,0) :: ((7,1,dippingAway,hangingWall,10) :: ((8,2,dippingAway,hangingWall,10) :: ((8,2,dippingAway,hangingWall,11) :: ((9,3,dippingAway,hangingWall,11) ::
				                                          ((9,3,dippingAway,hangingWall,12) :: ((16,16,dippingAway,hangingWall,12) :: ((0,0,dippingTowards,footWall,7) :: 
			                                                  ((10,1,dippingTowards,footWall,7) :: ((10,1,dippingTowards,footWall,8) :: ((11,2,dippingTowards,footWall,8) ::
				                                          ((11,2,dippingTowards,footWall,9) :: ((12,3,dippingTowards,footWall,9) :: ((12,3,dippingTowards,footWall,16) :: nil))))))))))))), Time: timeOf(Fault,1) >

   < 2 : Fault | FType: normalfault, Filling: non-sealing, InContactWith: (10,1,dippingAway,hangingWall,0) :: ((11,2,dippingAway,hangingWall,13) :: ((12,3,dippingAway,hangingWall,14) ::
				                                          ((16,16,dippingAway,hangingWall,15) :: ((0,0,dippingTowards,footWall,10) ::
			                                                  ((13,1,dippingTowards,footWall,11) ::
				                                          ((14,2,dippingTowards,footWall,12) :: ((15,3,dippingTowards,footWall,16) :: nil))))))), Time: timeOf(Fault,2) >

   < 3 : Fault | FType: normalfault, Filling: sealing, InContactWith:     (13,1,dippingAway,hangingWall,null) :: ((14,2,dippingAway,hangingWall,null) :: ((15,3,dippingAway,hangingWall,null) :: nil)), Time: timeOf(Fault,3) >	

   < 0 : GeoUnit  | GeoUnit: 0, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,0), Role: noRole, 
		 InContactWith: 13 :: (10 :: (7 :: (4 :: nil))), KerogenType: "none", Hydrocarbon: null >
	
   < 4 : GeoUnit  | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, --- sourceRock,
		 InContactWith: 5 :: nil, KerogenType: "3", Hydrocarbon: null > 
   < 5 : GeoUnit  | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: feederChannel, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 4 :: (6 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 6 : GeoUnit  | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole, 
		 InContactWith: 5 :: nil, KerogenType: "none", Hydrocarbon: null >
	  
   < 7 : GeoUnit  | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 8 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 8 : GeoUnit  | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: distributaryChannel, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 7 :: (9 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 9 : GeoUnit  | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole, 
		 InContactWith: 8 :: nil, KerogenType: "none", Hydrocarbon: null >

   < 10 : GeoUnit | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 11 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 11 : GeoUnit | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: lobe, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole,
		 InContactWith: 10 :: (12 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 12 : GeoUnit | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole,
		 InContactWith: 11 :: nil, KerogenType: "none", Hydrocarbon: null >
	
   < 13 : GeoUnit | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 14 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 14 : GeoUnit | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: lobe, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 13 :: (15 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 15 : GeoUnit | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole,
		 InContactWith: 14 :: nil, KerogenType: "none", Hydrocarbon: null >	

   < 16 : GeoUnit | GeoUnit: 16, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,16), Role: noRole,
		 InContactWith: 15 :: (12 :: (9 :: (6 :: nil))), KerogenType: "none", Hydrocarbon: null >

   ageComparison(younger(timeOf(GeoUnit,16),timeOf(GeoUnit,3)) :: younger(timeOf(GeoUnit,3),timeOf(GeoUnit,2)) ::
	         younger(timeOf(GeoUnit,2),timeOf(GeoUnit,1)) :: younger(timeOf(GeoUnit,1),timeOf(GeoUnit,0)))
	
   depositionalContact((3,16) :: ((2,3) :: ((1,2) :: ((0,1) :: nil))))		    	
   younger(timeOf(Fault,0),timeOf(Migration))
   younger(timeOf(Migration),timeOf(Fault,3))

   --- default values ---
   trapformation(5,none,nil,undefined) trapformation(8,none,nil,undefined) trapformation(11,none,nil,undefined) trapformation(14,none,nil,undefined)
   accumulation(5,false) accumulation(8,false) accumulation(11,false) accumulation(14,false) 
   history("init") .


  op caseStudy2-2 : -> Configuration [ctor] . 
  eq caseStudy2-2
  = < GeoUnit | Ocnt: 17 > 
   < Hydrocarbon | Ocnt: 0 > 
   < Fault | Ocnt: 4 > 
   < Pathways | Pathways: nil, Ocnt: 0 > 

   < 0 : Fault | FType: normalfault, Filling: non-sealing, InContactWith: (4,1,dippingAway,hangingWall,0) :: ((5,2,dippingAway,hangingWall,0) :: ((5,2,dippingAway,hangingWall,7) :: ((6,3,dippingAway,hangingWall,7) ::
                                                                          ((6,3,dippingAway,hangingWall,8) :: ((16,16,dippingAway,hangingWall,8) :: ((16,16,dippingAway,hangingWall,9) :: ((0,0,dippingTowards,footWall,4) :: 
		                                                          ((0,0,dippingTowards,footWall,5) :: ((7,1,dippingTowards,footWall,5) :: ((7,1,dippingTowards,footWall,6) :: ((8,2,dippingTowards,footWall,6) ::
					                                  ((8,2,dippingTowards,footWall,16) :: ((9,3,dippingTowards,footWall,16) :: nil))))))))))))), Time: timeOf(Fault,0) >

   < 1 : Fault | FType: normalfault, Filling: non-sealing, InContactWith: (7,1,dippingAway,hangingWall,0) :: ((7,1,dippingAway,hangingWall,10) :: ((8,2,dippingAway,hangingWall,10) :: ((8,2,dippingAway,hangingWall,11) :: ((9,3,dippingAway,hangingWall,11) ::
				                                          ((9,3,dippingAway,hangingWall,12) :: ((16,16,dippingAway,hangingWall,12) :: ((0,0,dippingTowards,footWall,7) :: 
			                                                  ((10,1,dippingTowards,footWall,7) :: ((10,1,dippingTowards,footWall,8) :: ((11,2,dippingTowards,footWall,8) ::
				                                          ((11,2,dippingTowards,footWall,9) :: ((12,3,dippingTowards,footWall,9) :: ((12,3,dippingTowards,footWall,16) :: nil))))))))))))), Time: timeOf(Fault,1) >

   < 2 : Fault | FType: normalfault, Filling: non-sealing, InContactWith: (10,1,dippingAway,hangingWall,0) :: ((11,2,dippingAway,hangingWall,13) :: ((12,3,dippingAway,hangingWall,14) ::
				                                          ((16,16,dippingAway,hangingWall,15) :: ((0,0,dippingTowards,footWall,10) ::
			                                                  ((13,1,dippingTowards,footWall,11) ::
				                                          ((14,2,dippingTowards,footWall,12) :: ((15,3,dippingTowards,footWall,16) :: nil))))))), Time: timeOf(Fault,2) >

   < 3 : Fault | FType: normalfault, Filling: sealing, InContactWith:     (13,1,dippingAway,hangingWall,null) :: ((14,2,dippingAway,hangingWall,null) :: ((15,3,dippingAway,hangingWall,null) :: nil)), Time: timeOf(Fault,3) >

    
   < 0 : GeoUnit  | GeoUnit: 0, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,0), Role: noRole, 
		 InContactWith: 13 :: (10 :: (7 :: (4 :: nil))), KerogenType: "none", Hydrocarbon: null >
	
   < 4 : GeoUnit  | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, --- sourceRock,
		 InContactWith: 5 :: nil, KerogenType: "3", Hydrocarbon: null > 
   < 5 : GeoUnit  | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: feederChannel, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 4 :: (6 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 6 : GeoUnit  | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole, 
		 InContactWith: 5 :: nil, KerogenType: "none", Hydrocarbon: null >
	  
   < 7 : GeoUnit  | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 8 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 8 : GeoUnit  | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: distributaryChannel, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 7 :: (9 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 9 : GeoUnit  | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole, 
		 InContactWith: 8 :: nil, KerogenType: "none", Hydrocarbon: null >

   < 10 : GeoUnit | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 11 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 11 : GeoUnit | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: lobe, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole,
		 InContactWith: 10 :: (12 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 12 : GeoUnit | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole,
		 InContactWith: 11 :: nil, KerogenType: "none", Hydrocarbon: null >
	
   < 13 : GeoUnit | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 14 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 14 : GeoUnit | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: lobe, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 13 :: (15 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 15 : GeoUnit | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole,
		 InContactWith: 14 :: nil, KerogenType: "none", Hydrocarbon: null >	

   < 16 : GeoUnit | GeoUnit: 16, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,16), Role: noRole,
		 InContactWith: 15 :: (12 :: (9 :: (6 :: nil))), KerogenType: "none", Hydrocarbon: null >

   ageComparison(younger(timeOf(GeoUnit,16),timeOf(GeoUnit,3)) :: younger(timeOf(GeoUnit,3),timeOf(GeoUnit,2)) ::
	         younger(timeOf(GeoUnit,2),timeOf(GeoUnit,1)) :: younger(timeOf(GeoUnit,1),timeOf(GeoUnit,0)))
	
   depositionalContact((3,16) :: ((2,3) :: ((1,2) :: ((0,1) :: nil))))		    	
   younger(timeOf(Fault,3),timeOf(Migration))
  
   --- default values ---
   trapformation(5,none,nil,undefined) trapformation(8,none,nil,undefined) trapformation(11,none,nil,undefined) trapformation(14,none,nil,undefined)
   accumulation(5,false) accumulation(8,false) accumulation(11,false) accumulation(14,false) 
   history("init") .
    
    
  op caseStudy3-0 : -> Configuration [ctor] . 
  eq caseStudy3-0
  = < GeoUnit | Ocnt: 17 > 
   < Hydrocarbon | Ocnt: 0 > 
   < Fault | Ocnt: 4 > 
   < Pathways | Pathways: nil, Ocnt: 0 > 

   < 0 : Fault | FType: normalfault, Filling: non-sealing, InContactWith: (0,0,dippingAway,footWall,7) :: ((0,0,dippingAway,footWall,8) :: ((4,1,dippingAway,footWall,8) :: ((4,1,dippingAway,footWall,9) :: ((5,2,dippingAway,footWall,9) ::
			                                                 ((5,2,dippingAway,footWall,16) :: ((6,3,dippingAway,footWall,16) :: ((7,1,dippingTowards,hangingWall,0) :: ((8,2,dippingTowards,hangingWall,0) ::
				                                         ((8,2,dippingTowards,hangingWall,4) :: ((9,3,dippingTowards,hangingWall,4) :: ((9,3,dippingTowards,hangingWall,5) ::
					                                 ((16,16,dippingTowards,hangingWall,5) :: ((16,16,dippingTowards,hangingWall,6) :: nil))))))))))))), Time: timeOf(Fault,0) >

   < 1 : Fault | FType: normalfault, Filling: non-sealing, InContactWith: (0,0,dippingAway,footWall,10) :: ((7,1,dippingAway,footWall,10) :: ((7,1,dippingAway,footWall,11) :: ((8,2,dippingAway,footWall,11) :: 
				                                          ((8,2,dippingAway,footWall,12) :: ((9,3,dippingAway,footWall,12) ::((9,3,dippingAway,footWall,16) :: 
			                                                  ((10,1,dippingTowards,hangingWall,0) :: ((10,1,dippingTowards,hangingWall,7) :: ((11,2,dippingTowards,hangingWall,7) ::
				                                          ((11,2,dippingTowards,hangingWall,8) :: ((12,3,dippingTowards,hangingWall,8) :: ((12,3,dippingTowards,hangingWall,9) :: ((16,16,dippingTowards,hangingWall,9) :: nil))))))))))))), Time: timeOf(Fault,1) >

   < 2 : Fault | FType: normalfault, Filling: non-sealing, InContactWith: (0,0,dippingAway,footWall,13) :: ((10,1,dippingAway,footWall,14) :: ((11,2,dippingAway,footWall,15) :: ((12,3,dippingAway,footWall,16) ::
			                                                  ((13,1,dippingTowards,hangingWall,0) :: ((14,2,dippingTowards,hangingWall,10) ::
				                                          ((15,3,dippingTowards,hangingWall,11) :: ((16,16,dippingTowards,hangingWall,12) :: nil))))))), Time: timeOf(Fault,2) >

   < 3 : Fault | FType: normalfault, Filling: sealing, InContactWith:     (13,1,dippingAway,footWall,null) :: ((14,2,dippingAway,footWall,null) :: ((15,3,dippingAway,footWall,null) :: nil)), Time: timeOf(Fault,3) >	

   < 0 : GeoUnit  | GeoUnit: 0, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,0), Role: noRole, 
		 InContactWith: 13 :: (10 :: (7 :: (4 :: nil))), KerogenType: "none", Hydrocarbon: null >
	
   < 4 : GeoUnit  | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, --- sourceRock,
		 InContactWith: 5 :: nil, KerogenType: "3", Hydrocarbon: null > 
   < 5 : GeoUnit  | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: distributaryChannel, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 4 :: (6 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 6 : GeoUnit  | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole, 
		 InContactWith: 5 :: nil, KerogenType: "none", Hydrocarbon: null >
	  
   < 7 : GeoUnit  | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 8 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 8 : GeoUnit  | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: interChannel, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 7 :: (9 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 9 : GeoUnit  | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole, 
		 InContactWith: 8 :: nil, KerogenType: "none", Hydrocarbon: null >

   < 10 : GeoUnit | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 11 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 11 : GeoUnit | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: lobe, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole,
		 InContactWith: 10 :: (12 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 12 : GeoUnit | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole,
		 InContactWith: 11 :: nil, KerogenType: "none", Hydrocarbon: null >
	
   < 13 : GeoUnit | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 14 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 14 : GeoUnit | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: lobeFringe, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 13 :: (15 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 15 : GeoUnit | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole,
		 InContactWith: 14 :: nil, KerogenType: "none", Hydrocarbon: null >	

   < 16 : GeoUnit | GeoUnit: 16, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,16), Role: noRole,
		 InContactWith: 15 :: (12 :: (9 :: (6 :: nil))), KerogenType: "none", Hydrocarbon: null > 

   ageComparison(younger(timeOf(GeoUnit,16),timeOf(GeoUnit,3)) :: younger(timeOf(GeoUnit,3),timeOf(GeoUnit,2)) ::
	         younger(timeOf(GeoUnit,2),timeOf(GeoUnit,1)) :: younger(timeOf(GeoUnit,1),timeOf(GeoUnit,0)))
	
   depositionalContact((3,16) :: ((2,3) :: ((1,2) :: ((0,1) :: nil))))		    	
   younger(timeOf(Migration),timeOf(Fault,0)) 

   --- default values ---
   trapformation(5,none,nil,undefined) trapformation(8,none,nil,undefined) trapformation(11,none,nil,undefined) trapformation(14,none,nil,undefined)
   accumulation(5,false) accumulation(8,false) accumulation(11,false) accumulation(14,false) 
   history("init") .

    
  op caseStudy3-1 : -> Configuration [ctor] . 
  eq caseStudy3-1
  = < GeoUnit | Ocnt: 17 > 
   < Hydrocarbon | Ocnt: 0 > 
   < Fault | Ocnt: 4 > 
   < Pathways | Pathways: nil, Ocnt: 0 > 


   < 0 : Fault | FType: normalfault, Filling: non-sealing, InContactWith: (0,0,dippingAway,footWall,7) :: ((0,0,dippingAway,footWall,8) :: ((4,1,dippingAway,footWall,8) :: ((4,1,dippingAway,footWall,9) :: ((5,2,dippingAway,footWall,9) ::
			                                                 ((5,2,dippingAway,footWall,16) :: ((6,3,dippingAway,footWall,16) :: ((7,1,dippingTowards,hangingWall,0) :: ((8,2,dippingTowards,hangingWall,0) ::
				                                         ((8,2,dippingTowards,hangingWall,4) :: ((9,3,dippingTowards,hangingWall,4) :: ((9,3,dippingTowards,hangingWall,5) ::
					                                 ((16,16,dippingTowards,hangingWall,5) :: ((16,16,dippingTowards,hangingWall,6) :: nil))))))))))))), Time: timeOf(Fault,0) >

   < 1 : Fault | FType: normalfault, Filling: non-sealing, InContactWith: (0,0,dippingAway,footWall,10) :: ((7,1,dippingAway,footWall,10) :: ((7,1,dippingAway,footWall,11) :: ((8,2,dippingAway,footWall,11) :: 
				                                          ((8,2,dippingAway,footWall,12) :: ((9,3,dippingAway,footWall,12) ::((9,3,dippingAway,footWall,16) :: 
			                                                  ((10,1,dippingTowards,hangingWall,0) :: ((10,1,dippingTowards,hangingWall,7) :: ((11,2,dippingTowards,hangingWall,7) ::
				                                          ((11,2,dippingTowards,hangingWall,8) :: ((12,3,dippingTowards,hangingWall,8) :: ((12,3,dippingTowards,hangingWall,9) :: ((16,16,dippingTowards,hangingWall,9) :: nil))))))))))))), Time: timeOf(Fault,1) >

   < 2 : Fault | FType: normalfault, Filling: non-sealing, InContactWith: (0,0,dippingAway,footWall,13) :: ((10,1,dippingAway,footWall,14) :: ((11,2,dippingAway,footWall,15) :: ((12,3,dippingAway,footWall,16) ::
			                                                  ((13,1,dippingTowards,hangingWall,0) :: ((14,2,dippingTowards,hangingWall,10) ::
				                                          ((15,3,dippingTowards,hangingWall,11) :: ((16,16,dippingTowards,hangingWall,12) :: nil))))))), Time: timeOf(Fault,2) >

   < 3 : Fault | FType: normalfault, Filling: sealing, InContactWith:     (13,1,dippingAway,footWall,null) :: ((14,2,dippingAway,footWall,null) :: ((15,3,dippingAway,footWall,null) :: nil)), Time: timeOf(Fault,3) >	

   < 0 : GeoUnit  | GeoUnit: 0, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,0), Role: noRole, 
		 InContactWith: 13 :: (10 :: (7 :: (4 :: nil))), KerogenType: "none", Hydrocarbon: null >
	
   < 4 : GeoUnit  | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, --- sourceRock,
		 InContactWith: 5 :: nil, KerogenType: "3", Hydrocarbon: null > 
   < 5 : GeoUnit  | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: feederChannel, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 4 :: (6 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 6 : GeoUnit  | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole, 
		 InContactWith: 5 :: nil, KerogenType: "none", Hydrocarbon: null >
	  
   < 7 : GeoUnit  | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 8 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 8 : GeoUnit  | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: distributaryChannel, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 7 :: (9 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 9 : GeoUnit  | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole, 
		 InContactWith: 8 :: nil, KerogenType: "none", Hydrocarbon: null >

   < 10 : GeoUnit | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 11 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 11 : GeoUnit | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: lobe, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole,
		 InContactWith: 10 :: (12 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 12 : GeoUnit | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole,
		 InContactWith: 11 :: nil, KerogenType: "none", Hydrocarbon: null >
	
   < 13 : GeoUnit | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 14 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 14 : GeoUnit | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: lobe, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 13 :: (15 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 15 : GeoUnit | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole,
		 InContactWith: 14 :: nil, KerogenType: "none", Hydrocarbon: null >	

   < 16 : GeoUnit | GeoUnit: 16, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,16), Role: noRole,
		 InContactWith: 15 :: (12 :: (9 :: (6 :: nil))), KerogenType: "none", Hydrocarbon: null > 

   ageComparison(younger(timeOf(GeoUnit,16),timeOf(GeoUnit,3)) :: younger(timeOf(GeoUnit,3),timeOf(GeoUnit,2)) ::
	         younger(timeOf(GeoUnit,2),timeOf(GeoUnit,1)) :: younger(timeOf(GeoUnit,1),timeOf(GeoUnit,0)))
	
   depositionalContact((3,16) :: ((2,3) :: ((1,2) :: ((0,1) :: nil))))		    	
   younger(timeOf(Fault,0),timeOf(Migration))
   younger(timeOf(Migration),timeOf(Fault,3))

   --- default values ---
   trapformation(5,none,nil,undefined) trapformation(8,none,nil,undefined) trapformation(11,none,nil,undefined) trapformation(14,none,nil,undefined)
   accumulation(5,false) accumulation(8,false) accumulation(11,false) accumulation(14,false) 
   history("init") .


    
  op caseStudy3-2 : -> Configuration [ctor] . 
  eq caseStudy3-2
  = < GeoUnit | Ocnt: 17 > 
   < Hydrocarbon | Ocnt: 0 > 
   < Fault | Ocnt: 4 > 
   < Pathways | Pathways: nil, Ocnt: 0 > 


   < 0 : Fault | FType: normalfault, Filling: non-sealing, InContactWith: (0,0,dippingAway,footWall,7) :: ((0,0,dippingAway,footWall,8) :: ((4,1,dippingAway,footWall,8) :: ((4,1,dippingAway,footWall,9) :: ((5,2,dippingAway,footWall,9) ::
			                                                 ((5,2,dippingAway,footWall,16) :: ((6,3,dippingAway,footWall,16) :: ((7,1,dippingTowards,hangingWall,0) :: ((8,2,dippingTowards,hangingWall,0) ::
				                                         ((8,2,dippingTowards,hangingWall,4) :: ((9,3,dippingTowards,hangingWall,4) :: ((9,3,dippingTowards,hangingWall,5) ::
					                                 ((16,16,dippingTowards,hangingWall,5) :: ((16,16,dippingTowards,hangingWall,6) :: nil))))))))))))), Time: timeOf(Fault,0) >

   < 1 : Fault | FType: normalfault, Filling: non-sealing, InContactWith: (0,0,dippingAway,footWall,10) :: ((7,1,dippingAway,footWall,10) :: ((7,1,dippingAway,footWall,11) :: ((8,2,dippingAway,footWall,11) :: 
				                                          ((8,2,dippingAway,footWall,12) :: ((9,3,dippingAway,footWall,12) ::((9,3,dippingAway,footWall,16) :: 
			                                                  ((10,1,dippingTowards,hangingWall,0) :: ((10,1,dippingTowards,hangingWall,7) :: ((11,2,dippingTowards,hangingWall,7) ::
				                                          ((11,2,dippingTowards,hangingWall,8) :: ((12,3,dippingTowards,hangingWall,8) :: ((12,3,dippingTowards,hangingWall,9) :: ((16,16,dippingTowards,hangingWall,9) :: nil))))))))))))), Time: timeOf(Fault,1) >

   < 2 : Fault | FType: normalfault, Filling: non-sealing, InContactWith: (0,0,dippingAway,footWall,13) :: ((10,1,dippingAway,footWall,14) :: ((11,2,dippingAway,footWall,15) :: ((12,3,dippingAway,footWall,16) ::
			                                                  ((13,1,dippingTowards,hangingWall,0) :: ((14,2,dippingTowards,hangingWall,10) ::
				                                          ((15,3,dippingTowards,hangingWall,11) :: ((16,16,dippingTowards,hangingWall,12) :: nil))))))), Time: timeOf(Fault,2) >

   < 3 : Fault | FType: normalfault, Filling: sealing, InContactWith:     (13,1,dippingAway,footWall,null) :: ((14,2,dippingAway,footWall,null) :: ((15,3,dippingAway,footWall,null) :: nil)), Time: timeOf(Fault,3) >

    
   < 0 : GeoUnit  | GeoUnit: 0, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,0), Role: noRole, 
		 InContactWith: 13 :: (10 :: (7 :: (4 :: nil))), KerogenType: "none", Hydrocarbon: null >
	
   < 4 : GeoUnit  | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, --- sourceRock,
		 InContactWith: 5 :: nil, KerogenType: "3", Hydrocarbon: null > 
   < 5 : GeoUnit  | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: feederChannel, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 4 :: (6 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 6 : GeoUnit  | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole, 
		 InContactWith: 5 :: nil, KerogenType: "none", Hydrocarbon: null >
	  
   < 7 : GeoUnit  | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 8 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 8 : GeoUnit  | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: distributaryChannel, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 7 :: (9 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 9 : GeoUnit  | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole, 
		 InContactWith: 8 :: nil, KerogenType: "none", Hydrocarbon: null >

   < 10 : GeoUnit | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 11 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 11 : GeoUnit | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: lobe, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole,
		 InContactWith: 10 :: (12 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 12 : GeoUnit | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole,
		 InContactWith: 11 :: nil, KerogenType: "none", Hydrocarbon: null >
	
   < 13 : GeoUnit | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 14 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 14 : GeoUnit | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: lobe, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 13 :: (15 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 15 : GeoUnit | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole,
		 InContactWith: 14 :: nil, KerogenType: "none", Hydrocarbon: null >	

   < 16 : GeoUnit | GeoUnit: 16, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,16), Role: noRole,
		 InContactWith: 15 :: (12 :: (9 :: (6 :: nil))), KerogenType: "none", Hydrocarbon: null > 

   ageComparison(younger(timeOf(GeoUnit,16),timeOf(GeoUnit,3)) :: younger(timeOf(GeoUnit,3),timeOf(GeoUnit,2)) ::
	         younger(timeOf(GeoUnit,2),timeOf(GeoUnit,1)) :: younger(timeOf(GeoUnit,1),timeOf(GeoUnit,0)))
	
   depositionalContact((3,16) :: ((2,3) :: ((1,2) :: ((0,1) :: nil))))		    	
   younger(timeOf(Fault,3),timeOf(Migration))

   --- default values ---
   trapformation(5,none,nil,undefined) trapformation(8,none,nil,undefined) trapformation(11,none,nil,undefined) trapformation(14,none,nil,undefined)
   accumulation(5,false) accumulation(8,false) accumulation(11,false) accumulation(14,false) 
   history("init") .


    
  op caseStudy4-0 : -> Configuration [ctor] .
  eq caseStudy4-0
  = < GeoUnit | Ocnt: 17 > 
   < Hydrocarbon | Ocnt: 0 > 
   < Fault | Ocnt: 4 > 
   < Pathways | Pathways: nil, Ocnt: 0 > 

   < 0 : Fault | FType: reversefault, Filling: non-sealing, InContactWith: (4,1,dippingAway,footWall,0) :: ((5,2,dippingAway,footWall,0) :: ((5,2,dippingAway,footWall,7) :: ((6,3,dippingAway,footWall,7) :: ((6,3,dippingAway,footWall,8) ::
                                                                          ((16,16,dippingAway,footWall,8) :: ((16,16,dippingAway,footWall,9) :: ((0,0,dippingTowards,hangingWall,4) ::
		                                                          ((0,0,dippingTowards,hangingWall,5) :: ((7,1,dippingTowards,hangingWall,5) :: ((7,1,dippingTowards,hangingWall,6) ::
			                                                  ((8,2,dippingTowards,hangingWall,6) :: ((8,2,dippingTowards,hangingWall,16) :: ((9,3,dippingTowards,hangingWall,16) :: nil))))))))))))), Time: timeOf(Fault,0) >

   < 1 : Fault | FType: reversefault, Filling: non-sealing, InContactWith: (7,1,dippingAway,footWall,0) :: ((7,1,dippingAway,footWall,10) :: ((8,2,dippingAway,footWall,10) :: ((8,2,dippingAway,footWall,11) :: ((9,3,dippingAway,footWall,11) ::
				                                          ((9,3,dippingAway,footWall,12) :: ((16,16,dippingAway,footWall,12) :: ((0,0,dippingTowards,hangingWall,7) :: 
			                                                  ((10,1,dippingTowards,hangingWall,7) :: ((10,1,dippingTowards,hangingWall,8) :: ((11,2,dippingTowards,hangingWall,8) ::
				                                          ((11,2,dippingTowards,hangingWall,9) :: ((12,3,dippingTowards,hangingWall,9) :: ((12,3,dippingTowards,hangingWall,16) :: nil))))))))))))), Time: timeOf(Fault,1) >

   < 2 : Fault | FType: reversefault, Filling: non-sealing, InContactWith: (10,1,dippingAway,footWall,0) :: ((11,2,dippingAway,footWall,13) :: ((12,3,dippingAway,footWall,14) :: ((16,16,dippingAway,footWall,15) ::
			                                                  ((0,0,dippingTowards,hangingWall,10) :: ((13,1,dippingTowards,hangingWall,11) ::  
				                                          ((14,2,dippingTowards,hangingWall,12) :: ((15,3,dippingTowards,hangingWall,16) :: nil))))))), Time: timeOf(Fault,2) >

   < 3 : Fault | FType: reversefault, Filling: sealing, InContactWith:     (13,1,dippingAway,footWall,null) :: ((14,2,dippingAway,footWall,null) :: ((15,3,dippingAway,footWall,null) :: nil)), Time: timeOf(Fault,3) >	

   < 0 : GeoUnit  | GeoUnit: 0, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,0), Role: noRole, 
		 InContactWith: 13 :: (10 :: (7 :: (4 :: nil))), KerogenType: "none", Hydrocarbon: null >
	
   < 4 : GeoUnit  | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, --- sourceRock,
		 InContactWith: 5 :: nil, KerogenType: "3", Hydrocarbon: null > 
   < 5 : GeoUnit  | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: distributaryChannel, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 4 :: (6 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 6 : GeoUnit  | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole, 
		 InContactWith: 5 :: nil, KerogenType: "none", Hydrocarbon: null >
	  
   < 7 : GeoUnit  | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 8 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 8 : GeoUnit  | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: interChannel, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 7 :: (9 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 9 : GeoUnit  | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole, 
		 InContactWith: 8 :: nil, KerogenType: "none", Hydrocarbon: null >

   < 10 : GeoUnit | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 11 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 11 : GeoUnit | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: lobe, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole,
		 InContactWith: 10 :: (12 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 12 : GeoUnit | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole,
		 InContactWith: 11 :: nil, KerogenType: "none", Hydrocarbon: null >
	
   < 13 : GeoUnit | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 14 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 14 : GeoUnit | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: lobeFringe, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 13 :: (15 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 15 : GeoUnit | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole,
		 InContactWith: 14 :: nil, KerogenType: "none", Hydrocarbon: null >	

   < 16 : GeoUnit | GeoUnit: 16, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,16), Role: noRole,
		 InContactWith: 15 :: (12 :: (9 :: (6 :: nil))), KerogenType: "none", Hydrocarbon: null >   

   ageComparison(younger(timeOf(GeoUnit,16),timeOf(GeoUnit,3)) :: younger(timeOf(GeoUnit,3),timeOf(GeoUnit,2)) ::
	         younger(timeOf(GeoUnit,2),timeOf(GeoUnit,1)) :: younger(timeOf(GeoUnit,1),timeOf(GeoUnit,0)))
	
   depositionalContact((3,16) :: ((2,3) :: ((1,2) :: ((0,1) :: nil))))		    	
   younger(timeOf(Migration),timeOf(Fault,0))   
 
   --- default values ---
   trapformation(5,none,nil,undefined) trapformation(8,none,nil,undefined) trapformation(11,none,nil,undefined) trapformation(14,none,nil,undefined)
   accumulation(5,false) accumulation(8,false) accumulation(11,false) accumulation(14,false) 
   history("init") .


    
  op caseStudy4-1 : -> Configuration [ctor] . 
  eq caseStudy4-1
  = < GeoUnit | Ocnt: 17 > 
   < Hydrocarbon | Ocnt: 0 > 
   < Fault | Ocnt: 4 > 
   < Pathways | Pathways: nil, Ocnt: 0 > 

   < 0 : Fault | FType: reversefault, Filling: non-sealing, InContactWith: (4,1,dippingAway,footWall,0) :: ((5,2,dippingAway,footWall,0) :: ((5,2,dippingAway,footWall,7) :: ((6,3,dippingAway,footWall,7) :: ((6,3,dippingAway,footWall,8) ::
                                                                          ((16,16,dippingAway,footWall,8) :: ((16,16,dippingAway,footWall,9) :: ((0,0,dippingTowards,hangingWall,4) ::
		                                                          ((0,0,dippingTowards,hangingWall,5) :: ((7,1,dippingTowards,hangingWall,5) :: ((7,1,dippingTowards,hangingWall,6) ::
			                                                  ((8,2,dippingTowards,hangingWall,6) :: ((8,2,dippingTowards,hangingWall,16) :: ((9,3,dippingTowards,hangingWall,16) :: nil))))))))))))), Time: timeOf(Fault,0) >

   < 1 : Fault | FType: reversefault, Filling: non-sealing, InContactWith: (7,1,dippingAway,footWall,0) :: ((7,1,dippingAway,footWall,10) :: ((8,2,dippingAway,footWall,10) :: ((8,2,dippingAway,footWall,11) :: ((9,3,dippingAway,footWall,11) ::
				                                          ((9,3,dippingAway,footWall,12) :: ((16,16,dippingAway,footWall,12) :: ((0,0,dippingTowards,hangingWall,7) :: 
			                                                  ((10,1,dippingTowards,hangingWall,7) :: ((10,1,dippingTowards,hangingWall,8) :: ((11,2,dippingTowards,hangingWall,8) ::
				                                          ((11,2,dippingTowards,hangingWall,9) :: ((12,3,dippingTowards,hangingWall,9) :: ((12,3,dippingTowards,hangingWall,16) :: nil))))))))))))), Time: timeOf(Fault,1) >

   < 2 : Fault | FType: reversefault, Filling: non-sealing, InContactWith: (10,1,dippingAway,footWall,0) :: ((11,2,dippingAway,footWall,13) :: ((12,3,dippingAway,footWall,14) :: ((16,16,dippingAway,footWall,15) ::
			                                                  ((0,0,dippingTowards,hangingWall,10) :: ((13,1,dippingTowards,hangingWall,11) ::  
				                                          ((14,2,dippingTowards,hangingWall,12) :: ((15,3,dippingTowards,hangingWall,16) :: nil))))))), Time: timeOf(Fault,2) >

   < 3 : Fault | FType: reversefault, Filling: sealing, InContactWith:     (13,1,dippingAway,footWall,null) :: ((14,2,dippingAway,footWall,null) :: ((15,3,dippingAway,footWall,null) :: nil)), Time: timeOf(Fault,3) >	

	
   < 0 : GeoUnit  | GeoUnit: 0, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,0), Role: noRole, 
		 InContactWith: 13 :: (10 :: (7 :: (4 :: nil))), KerogenType: "none", Hydrocarbon: null >
	
   < 4 : GeoUnit  | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, --- sourceRock,
		 InContactWith: 5 :: nil, KerogenType: "3", Hydrocarbon: null > 
   < 5 : GeoUnit  | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: feederChannel, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 4 :: (6 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 6 : GeoUnit  | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole, 
		 InContactWith: 5 :: nil, KerogenType: "none", Hydrocarbon: null >
	  
   < 7 : GeoUnit  | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 8 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 8 : GeoUnit  | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: distributaryChannel, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 7 :: (9 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 9 : GeoUnit  | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole, 
		 InContactWith: 8 :: nil, KerogenType: "none", Hydrocarbon: null >

   < 10 : GeoUnit | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 11 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 11 : GeoUnit | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: lobe, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole,
		 InContactWith: 10 :: (12 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 12 : GeoUnit | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole,
		 InContactWith: 11 :: nil, KerogenType: "none", Hydrocarbon: null >
	
   < 13 : GeoUnit | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 14 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 14 : GeoUnit | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: lobe, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 13 :: (15 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 15 : GeoUnit | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole,
		 InContactWith: 14 :: nil, KerogenType: "none", Hydrocarbon: null >	

   < 16 : GeoUnit | GeoUnit: 16, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,16), Role: noRole,
		 InContactWith: 15 :: (12 :: (9 :: (6 :: nil))), KerogenType: "none", Hydrocarbon: null >

   ageComparison(younger(timeOf(GeoUnit,16),timeOf(GeoUnit,3)) :: younger(timeOf(GeoUnit,3),timeOf(GeoUnit,2)) ::
	         younger(timeOf(GeoUnit,2),timeOf(GeoUnit,1)) :: younger(timeOf(GeoUnit,1),timeOf(GeoUnit,0)))
	
   depositionalContact((3,16) :: ((2,3) :: ((1,2) :: ((0,1) :: nil))))		    	
   younger(timeOf(Fault,0),timeOf(Migration))
   younger(timeOf(Migration),timeOf(Fault,3))

   --- default values ---
   trapformation(5,none,nil,undefined) trapformation(8,none,nil,undefined) trapformation(11,none,nil,undefined) trapformation(14,none,nil,undefined)
   accumulation(5,false) accumulation(8,false) accumulation(11,false) accumulation(14,false) 
   history("init") .


    
  op caseStudy4-2 : -> Configuration [ctor] . 
  eq caseStudy4-2
  = < GeoUnit | Ocnt: 17 > 
   < Hydrocarbon | Ocnt: 0 > 
   < Fault | Ocnt: 4 > 
   < Pathways | Pathways: nil, Ocnt: 0 > 

   < 0 : Fault | FType: reversefault, Filling: non-sealing, InContactWith: (4,1,dippingAway,footWall,0) :: ((5,2,dippingAway,footWall,0) :: ((5,2,dippingAway,footWall,7) :: ((6,3,dippingAway,footWall,7) :: ((6,3,dippingAway,footWall,8) ::
                                                                          ((16,16,dippingAway,footWall,8) :: ((16,16,dippingAway,footWall,9) :: ((0,0,dippingTowards,hangingWall,4) ::
		                                                          ((0,0,dippingTowards,hangingWall,5) :: ((7,1,dippingTowards,hangingWall,5) :: ((7,1,dippingTowards,hangingWall,6) ::
			                                                  ((8,2,dippingTowards,hangingWall,6) :: ((8,2,dippingTowards,hangingWall,16) :: ((9,3,dippingTowards,hangingWall,16) :: nil))))))))))))), Time: timeOf(Fault,0) >

   < 1 : Fault | FType: reversefault, Filling: non-sealing, InContactWith: (7,1,dippingAway,footWall,0) :: ((7,1,dippingAway,footWall,10) :: ((8,2,dippingAway,footWall,10) :: ((8,2,dippingAway,footWall,11) :: ((9,3,dippingAway,footWall,11) ::
				                                          ((9,3,dippingAway,footWall,12) :: ((16,16,dippingAway,footWall,12) :: ((0,0,dippingTowards,hangingWall,7) :: 
			                                                  ((10,1,dippingTowards,hangingWall,7) :: ((10,1,dippingTowards,hangingWall,8) :: ((11,2,dippingTowards,hangingWall,8) ::
				                                          ((11,2,dippingTowards,hangingWall,9) :: ((12,3,dippingTowards,hangingWall,9) :: ((12,3,dippingTowards,hangingWall,16) :: nil))))))))))))), Time: timeOf(Fault,1) >

   < 2 : Fault | FType: reversefault, Filling: non-sealing, InContactWith: (10,1,dippingAway,footWall,0) :: ((11,2,dippingAway,footWall,13) :: ((12,3,dippingAway,footWall,14) :: ((16,16,dippingAway,footWall,15) ::
			                                                  ((0,0,dippingTowards,hangingWall,10) :: ((13,1,dippingTowards,hangingWall,11) ::  
				                                          ((14,2,dippingTowards,hangingWall,12) :: ((15,3,dippingTowards,hangingWall,16) :: nil))))))), Time: timeOf(Fault,2) >

   < 3 : Fault | FType: reversefault, Filling: sealing, InContactWith:     (13,1,dippingAway,footWall,null) :: ((14,2,dippingAway,footWall,null) :: ((15,3,dippingAway,footWall,null) :: nil)), Time: timeOf(Fault,3) >


   < 0 : GeoUnit  | GeoUnit: 0, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,0), Role: noRole, 
		 InContactWith: 13 :: (10 :: (7 :: (4 :: nil))), KerogenType: "none", Hydrocarbon: null >
	
   < 4 : GeoUnit  | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, --- sourceRock,
		 InContactWith: 5 :: nil, KerogenType: "3", Hydrocarbon: null > 
   < 5 : GeoUnit  | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: feederChannel, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 4 :: (6 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 6 : GeoUnit  | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole, 
		 InContactWith: 5 :: nil, KerogenType: "none", Hydrocarbon: null >
	  
   < 7 : GeoUnit  | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 8 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 8 : GeoUnit  | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: distributaryChannel, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 7 :: (9 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 9 : GeoUnit  | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole, 
		 InContactWith: 8 :: nil, KerogenType: "none", Hydrocarbon: null >

   < 10 : GeoUnit | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 11 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 11 : GeoUnit | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: lobe, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole,
		 InContactWith: 10 :: (12 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 12 : GeoUnit | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole,
		 InContactWith: 11 :: nil, KerogenType: "none", Hydrocarbon: null >
	
   < 13 : GeoUnit | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 14 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 14 : GeoUnit | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: lobe, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 13 :: (15 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 15 : GeoUnit | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole,
		 InContactWith: 14 :: nil, KerogenType: "none", Hydrocarbon: null >	

   < 16 : GeoUnit | GeoUnit: 16, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,16), Role: noRole,
		 InContactWith: 15 :: (12 :: (9 :: (6 :: nil))), KerogenType: "none", Hydrocarbon: null >

   ageComparison(younger(timeOf(GeoUnit,16),timeOf(GeoUnit,3)) :: younger(timeOf(GeoUnit,3),timeOf(GeoUnit,2)) ::
	         younger(timeOf(GeoUnit,2),timeOf(GeoUnit,1)) :: younger(timeOf(GeoUnit,1),timeOf(GeoUnit,0)))
	
   depositionalContact((3,16) :: ((2,3) :: ((1,2) :: ((0,1) :: nil))))		    	
   younger(timeOf(Fault,3),timeOf(Migration))

   --- default values ---
   trapformation(5,none,nil,undefined) trapformation(8,none,nil,undefined) trapformation(11,none,nil,undefined) trapformation(14,none,nil,undefined)
   accumulation(5,false) accumulation(8,false) accumulation(11,false) accumulation(14,false) 
   history("init") .

    
    
   op caseStudy5-0 : -> Configuration [ctor] .
   eq caseStudy5-0
   = < GeoUnit | Ocnt: 17 > 
   < Hydrocarbon | Ocnt: 0 >
   < Fault | Ocnt: 4 > 
   < Pathways | Pathways: nil, Ocnt: 0 > 

   < 0 : Fault | FType: normalfault, Filling: non-sealing, InContactWith: (0,0,dippingAway,hangingWall,7) :: ((4,1,dippingAway,hangingWall,7) :: ((4,1,dippingAway,hangingWall,8) :: ((5,2,dippingAway,hangingWall,8) ::
			                                                  ((5,2,dippingAway,hangingWall,9) :: ((6,3,dippingAway,hangingWall,9) :: ((6,3,dippingAway,hangingWall,16) ::
		                                                          ((7,1,dippingTowards,footWall,0) :: ((7,1,dippingTowards,footWall,4) :: ((8,2,dippingTowards,footWall,4) :: ((8,2,dippingTowards,footWall,5) ::
				                                          ((9,3,dippingTowards,footWall,5) :: ((9,3,dippingTowards,footWall,6) :: ((16,16,dippingTowards,footWall,6) :: nil))))))))))))), Time: timeOf(Fault,0) >

   < 1 : Fault | FType: normalfault, Filling: non-sealing, InContactWith: (0,0,dippingAway,hangingWall,10) :: ((7,1,dippingAway,hangingWall,10) :: ((7,1,dippingAway,hangingWall,11) :: ((8,2,dippingAway,hangingWall,11) ::
			                                                  ((8,2,dippingAway,hangingWall,12) :: ((9,3,dippingAway,hangingWall,12) :: ((9,3,dippingAway,hangingWall,16) :: ((10,1,dippingTowards,footWall,0) ::
				                                          ((10,1,dippingTowards,footWall,7) :: ((11,2,dippingTowards,footWall,7) :: ((11,2,dippingTowards,footWall,8) :: ((12,3,dippingTowards,footWall,8) ::
				                                          ((12,3,dippingTowards,footWall,9) :: ((16,16,dippingTowards,footWall,9) ::  nil))))))))))))), Time: timeOf(Fault,1) >

   < 2 : Fault | FType: normalfault, Filling: non-sealing, InContactWith: (0,0,dippingAway,hangingWall,13) :: ((10,1,dippingAway,hangingWall,13) :: ((10,1,dippingAway,hangingWall,14) :: ((11,2,dippingAway,hangingWall,14) ::
		                                                         ((11,2,dippingAway,hangingWall,15) :: ((12,3,dippingAway,hangingWall,15) :: ((12,3,dippingAway,hangingWall,16) ::  ((13,1,dippingTowards,footWall,0) ::
			                                                 ((13,1,dippingTowards,footWall,10) :: ((14,2,dippingTowards,footWall,10) :: ((14,2,dippingTowards,footWall,11) :: ((15,3,dippingTowards,footWall,11) ::
					                                 ((15,3,dippingTowards,footWall,12) :: ((16,16,dippingTowards,footWall,12) :: nil))))))))))))), Time: timeOf(Fault,2) >

   < 3 : Fault | FType: normalfault, Filling: sealing, InContactWith:     (13,1,dippingAway,hangingWall,null) :: ((14,2,dippingAway,hangingWall,null) :: ((15,3,dippingAway,hangingWall,null) :: nil)), Time: timeOf(Fault,3) >	


	
   < 0 : GeoUnit  | GeoUnit: 0, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,0), Role: noRole, 
		 InContactWith: 13 :: (10 :: (7 :: (4 :: nil))), KerogenType: "none", Hydrocarbon: null >
	
   < 4 : GeoUnit  | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, --- sourceRock,
		 InContactWith: 5 :: nil, KerogenType: "3", Hydrocarbon: null > 
   < 5 : GeoUnit  | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: distributaryChannel, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 4 :: (6 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 6 : GeoUnit  | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole, 
		 InContactWith: 5 :: nil, KerogenType: "none", Hydrocarbon: null >
	  
   < 7 : GeoUnit  | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 8 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 8 : GeoUnit  | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: interChannel, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 7 :: (9 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 9 : GeoUnit  | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole, 
		 InContactWith: 8 :: nil, KerogenType: "none", Hydrocarbon: null >

   < 10 : GeoUnit | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 11 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 11 : GeoUnit | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: lobe, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole,
		 InContactWith: 10 :: (12 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 12 : GeoUnit | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole,
		 InContactWith: 11 :: nil, KerogenType: "none", Hydrocarbon: null >
	
   < 13 : GeoUnit | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 14 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 14 : GeoUnit | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: lobeFringe, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 13 :: (15 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 15 : GeoUnit | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole,
		 InContactWith: 14 :: nil, KerogenType: "none", Hydrocarbon: null >	

   < 16 : GeoUnit | GeoUnit: 16, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,16), Role: noRole,
		 InContactWith: 15 :: (12 :: (9 :: (6 :: nil))), KerogenType: "none", Hydrocarbon: null >   

   ageComparison(younger(timeOf(GeoUnit,16),timeOf(GeoUnit,3)) :: younger(timeOf(GeoUnit,3),timeOf(GeoUnit,2)) ::
	         younger(timeOf(GeoUnit,2),timeOf(GeoUnit,1)) :: younger(timeOf(GeoUnit,1),timeOf(GeoUnit,0)))
	
   depositionalContact((3,16) :: ((2,3) :: ((1,2) :: ((0,1) :: nil))))		    	
   younger(timeOf(Migration),timeOf(Fault,0)) 

   --- default values ---
   trapformation(5,none,nil,undefined) trapformation(8,none,nil,undefined) trapformation(11,none,nil,undefined) trapformation(14,none,nil,undefined)
   accumulation(5,false) accumulation(8,false) accumulation(11,false) accumulation(14,false) 
   history("init") .    


    
   op caseStudy5-1 : -> Configuration [ctor] . 
   eq caseStudy5-1
   = < GeoUnit | Ocnt: 17 > 
   < Hydrocarbon | Ocnt: 0 >
   < Fault | Ocnt: 4 > 
   < Pathways | Pathways: nil, Ocnt: 0 > 

   < 0 : Fault | FType: normalfault, Filling: non-sealing, InContactWith: (0,0,dippingAway,hangingWall,7) :: ((4,1,dippingAway,hangingWall,7) :: ((4,1,dippingAway,hangingWall,8) :: ((5,2,dippingAway,hangingWall,8) ::
			                                                  ((5,2,dippingAway,hangingWall,9) :: ((6,3,dippingAway,hangingWall,9) :: ((6,3,dippingAway,hangingWall,16) ::
		                                                          ((7,1,dippingTowards,footWall,0) :: ((7,1,dippingTowards,footWall,4) :: ((8,2,dippingTowards,footWall,4) :: ((8,2,dippingTowards,footWall,5) ::
				                                          ((9,3,dippingTowards,footWall,5) :: ((9,3,dippingTowards,footWall,6) :: ((16,16,dippingTowards,footWall,6) :: nil))))))))))))), Time: timeOf(Fault,0) >

   < 1 : Fault | FType: normalfault, Filling: non-sealing, InContactWith: (0,0,dippingAway,hangingWall,10) :: ((7,1,dippingAway,hangingWall,10) :: ((7,1,dippingAway,hangingWall,11) :: ((8,2,dippingAway,hangingWall,11) ::
			                                                  ((8,2,dippingAway,hangingWall,12) :: ((9,3,dippingAway,hangingWall,12) :: ((9,3,dippingAway,hangingWall,16) :: ((10,1,dippingTowards,footWall,0) ::
				                                          ((10,1,dippingTowards,footWall,7) :: ((11,2,dippingTowards,footWall,7) :: ((11,2,dippingTowards,footWall,8) :: ((12,3,dippingTowards,footWall,8) ::
				                                          ((12,3,dippingTowards,footWall,9) :: ((16,16,dippingTowards,footWall,9) ::  nil))))))))))))), Time: timeOf(Fault,1) >

   < 2 : Fault | FType: normalfault, Filling: non-sealing, InContactWith: (0,0,dippingAway,hangingWall,13) :: ((10,1,dippingAway,hangingWall,13) :: ((10,1,dippingAway,hangingWall,14) :: ((11,2,dippingAway,hangingWall,14) ::
		                                                         ((11,2,dippingAway,hangingWall,15) :: ((12,3,dippingAway,hangingWall,15) :: ((12,3,dippingAway,hangingWall,16) ::  ((13,1,dippingTowards,footWall,0) ::
			                                                 ((13,1,dippingTowards,footWall,10) :: ((14,2,dippingTowards,footWall,10) :: ((14,2,dippingTowards,footWall,11) :: ((15,3,dippingTowards,footWall,11) ::
					                                 ((15,3,dippingTowards,footWall,12) :: ((16,16,dippingTowards,footWall,12) :: nil))))))))))))), Time: timeOf(Fault,2) >

   < 3 : Fault | FType: normalfault, Filling: sealing, InContactWith:     (13,1,dippingAway,hangingWall,null) :: ((14,2,dippingAway,hangingWall,null) :: ((15,3,dippingAway,hangingWall,null) :: nil)), Time: timeOf(Fault,3) >	


	
   < 0 : GeoUnit  | GeoUnit: 0, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,0), Role: noRole, 
		 InContactWith: 13 :: (10 :: (7 :: (4 :: nil))), KerogenType: "none", Hydrocarbon: null >
	
   < 4 : GeoUnit  | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, --- sourceRock,
		 InContactWith: 5 :: nil, KerogenType: "3", Hydrocarbon: null > 
   < 5 : GeoUnit  | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: feederChannel, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 4 :: (6 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 6 : GeoUnit  | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole, 
		 InContactWith: 5 :: nil, KerogenType: "none", Hydrocarbon: null >
	  
   < 7 : GeoUnit  | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 8 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 8 : GeoUnit  | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: distributaryChannel, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 7 :: (9 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 9 : GeoUnit  | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole, 
		 InContactWith: 8 :: nil, KerogenType: "none", Hydrocarbon: null >

   < 10 : GeoUnit | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 11 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 11 : GeoUnit | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: lobe, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole,
		 InContactWith: 10 :: (12 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 12 : GeoUnit | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole,
		 InContactWith: 11 :: nil, KerogenType: "none", Hydrocarbon: null >
	
   < 13 : GeoUnit | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 14 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 14 : GeoUnit | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: lobe, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 13 :: (15 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 15 : GeoUnit | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole,
		 InContactWith: 14 :: nil, KerogenType: "none", Hydrocarbon: null >	

   < 16 : GeoUnit | GeoUnit: 16, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,16), Role: noRole,
		 InContactWith: 15 :: (12 :: (9 :: (6 :: nil))), KerogenType: "none", Hydrocarbon: null >   

   ageComparison(younger(timeOf(GeoUnit,16),timeOf(GeoUnit,3)) :: younger(timeOf(GeoUnit,3),timeOf(GeoUnit,2)) ::
	         younger(timeOf(GeoUnit,2),timeOf(GeoUnit,1)) :: younger(timeOf(GeoUnit,1),timeOf(GeoUnit,0)))
	
   depositionalContact((3,16) :: ((2,3) :: ((1,2) :: ((0,1) :: nil))))		    	
   younger(timeOf(Fault,0),timeOf(Migration))
   younger(timeOf(Migration),timeOf(Fault,3))
  
   --- default values ---
   trapformation(5,none,nil,undefined) trapformation(8,none,nil,undefined) trapformation(11,none,nil,undefined) trapformation(14,none,nil,undefined)
   accumulation(5,false) accumulation(8,false) accumulation(11,false) accumulation(14,false) 
   history("init") .



   op caseStudy5-2 : -> Configuration [ctor] . 
   eq caseStudy5-2
   = < GeoUnit | Ocnt: 17 > 
   < Hydrocarbon | Ocnt: 0 >
   < Fault | Ocnt: 4 > 
   < Pathways | Pathways: nil, Ocnt: 0 > 

   < 0 : Fault | FType: normalfault, Filling: non-sealing, InContactWith: (0,0,dippingAway,hangingWall,7) :: ((4,1,dippingAway,hangingWall,7) :: ((4,1,dippingAway,hangingWall,8) :: ((5,2,dippingAway,hangingWall,8) ::
			                                                  ((5,2,dippingAway,hangingWall,9) :: ((6,3,dippingAway,hangingWall,9) :: ((6,3,dippingAway,hangingWall,16) ::
		                                                          ((7,1,dippingTowards,footWall,0) :: ((7,1,dippingTowards,footWall,4) :: ((8,2,dippingTowards,footWall,4) :: ((8,2,dippingTowards,footWall,5) ::
				                                          ((9,3,dippingTowards,footWall,5) :: ((9,3,dippingTowards,footWall,6) :: ((16,16,dippingTowards,footWall,6) :: nil))))))))))))), Time: timeOf(Fault,0) >

   < 1 : Fault | FType: normalfault, Filling: non-sealing, InContactWith: (0,0,dippingAway,hangingWall,10) :: ((7,1,dippingAway,hangingWall,10) :: ((7,1,dippingAway,hangingWall,11) :: ((8,2,dippingAway,hangingWall,11) ::
			                                                  ((8,2,dippingAway,hangingWall,12) :: ((9,3,dippingAway,hangingWall,12) :: ((9,3,dippingAway,hangingWall,16) :: ((10,1,dippingTowards,footWall,0) ::
				                                          ((10,1,dippingTowards,footWall,7) :: ((11,2,dippingTowards,footWall,7) :: ((11,2,dippingTowards,footWall,8) :: ((12,3,dippingTowards,footWall,8) ::
				                                          ((12,3,dippingTowards,footWall,9) :: ((16,16,dippingTowards,footWall,9) ::  nil))))))))))))), Time: timeOf(Fault,1) >

   < 2 : Fault | FType: normalfault, Filling: non-sealing, InContactWith: (0,0,dippingAway,hangingWall,13) :: ((10,1,dippingAway,hangingWall,13) :: ((10,1,dippingAway,hangingWall,14) :: ((11,2,dippingAway,hangingWall,14) ::
		                                                         ((11,2,dippingAway,hangingWall,15) :: ((12,3,dippingAway,hangingWall,15) :: ((12,3,dippingAway,hangingWall,16) ::  ((13,1,dippingTowards,footWall,0) ::
			                                                 ((13,1,dippingTowards,footWall,10) :: ((14,2,dippingTowards,footWall,10) :: ((14,2,dippingTowards,footWall,11) :: ((15,3,dippingTowards,footWall,11) ::
					                                 ((15,3,dippingTowards,footWall,12) :: ((16,16,dippingTowards,footWall,12) :: nil))))))))))))), Time: timeOf(Fault,2) >

	< 3 : Fault | FType: normalfault, Filling: sealing, InContactWith:     (13,1,dippingAway,hangingWall,null) :: ((14,2,dippingAway,hangingWall,null) :: ((15,3,dippingAway,hangingWall,null) :: nil)), Time: timeOf(Fault,3) >

    
   < 0 : GeoUnit  | GeoUnit: 0, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,0), Role: noRole, 
		 InContactWith: 13 :: (10 :: (7 :: (4 :: nil))), KerogenType: "none", Hydrocarbon: null >
	
   < 4 : GeoUnit  | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, --- sourceRock,
		 InContactWith: 5 :: nil, KerogenType: "3", Hydrocarbon: null > 
   < 5 : GeoUnit  | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: feederChannel, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 4 :: (6 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 6 : GeoUnit  | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole, 
		 InContactWith: 5 :: nil, KerogenType: "none", Hydrocarbon: null >
	  
   < 7 : GeoUnit  | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 8 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 8 : GeoUnit  | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: distributaryChannel, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 7 :: (9 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 9 : GeoUnit  | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole, 
		 InContactWith: 8 :: nil, KerogenType: "none", Hydrocarbon: null >

   < 10 : GeoUnit | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 11 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 11 : GeoUnit | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: lobe, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole,
		 InContactWith: 10 :: (12 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 12 : GeoUnit | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole,
		 InContactWith: 11 :: nil, KerogenType: "none", Hydrocarbon: null >
	
   < 13 : GeoUnit | GeoUnit: 1, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,1), Role: noRole, 
		 InContactWith: 14 :: nil, KerogenType: "none", Hydrocarbon: null > 
   < 14 : GeoUnit | GeoUnit: 2, Type: sandstone, Permeability: unknown, Porosity: unknown, SubmarineFan: lobe, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,2), Role: noRole, 
		 InContactWith: 13 :: (15 :: nil), KerogenType: "none", Hydrocarbon: null > 
   < 15 : GeoUnit | GeoUnit: 3, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,3), Role: noRole,
		 InContactWith: 14 :: nil, KerogenType: "none", Hydrocarbon: null >	

   < 16 : GeoUnit | GeoUnit: 16, Type: shale, Permeability: unknown, Porosity: unknown, SubmarineFan: basinPlain, Folded: false, DepositedIn: terrestrial, Time: timeOf(GeoUnit,16), Role: noRole,
		 InContactWith: 15 :: (12 :: (9 :: (6 :: nil))), KerogenType: "none", Hydrocarbon: null >   

   ageComparison(younger(timeOf(GeoUnit,16),timeOf(GeoUnit,3)) :: younger(timeOf(GeoUnit,3),timeOf(GeoUnit,2)) ::
	         younger(timeOf(GeoUnit,2),timeOf(GeoUnit,1)) :: younger(timeOf(GeoUnit,1),timeOf(GeoUnit,0)))
	
   depositionalContact((3,16) :: ((2,3) :: ((1,2) :: ((0,1) :: nil))))		    	
   younger(timeOf(Fault,3),timeOf(Migration))
  
   --- default values ---
   trapformation(5,none,nil,undefined) trapformation(8,none,nil,undefined) trapformation(11,none,nil,undefined) trapformation(14,none,nil,undefined)
   accumulation(5,false) accumulation(8,false) accumulation(11,false) accumulation(14,false) 
   history("init") .


    
endm


    
